version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    # Disable all pull requests for Docker dependencies
    open-pull-requests-limit: 0
    reviewers:
      - "cowprotocol/frontend"
    commit-message:
      prefix: "fix(deps-update): "
      prefix-development: "chore(dev-deps-update): "
    groups:
      dev-deps:
        dependency-type: "development"
      # uncomment if we decide that production updates can be grouped
      #prod-deps:
      #  dependency-type: "production"
