name: 'CLA Assistant'
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: 'CLA Assistant'
        if: 
          github.base_ref != 'main' && 
          startsWith(github.head_ref, 'uni-merge') == false && 
          ((github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target')
        # Alpha Release
        uses: gnosis/github-action@master
        # GitHub token, automatically provided to the action
        # (No need to define this secret in the repo settings)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-cla-document: 'https://github.com/cowprotocol/cla/blob/main/Cow%20Services%20CLA.md'
          branch: 'cla-signatures'
          allowlist: dependabot,mergify,alfetopito,anxolin,W3stside,nenadV91,annamsgeorge,avsavsavs,c3rnst,cmagan,josojo,davidalbela,fedgiac,fleupold,giacomolicari,GabrielCamba,nlordell,alongoni,elena-zh,henrypalacios,matextrem,ramirotw,fairlighteth
          empty-commit-flag: false
          blockchain-storage-flag: false
