name: Kanban flow (Review/QA)

on:
  pull_request:
    types:
      - opened
      - ready_for_review

jobs:
  automate-project-columns:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Find Linked Issues
        id: links
        uses: hossainemruz/linked-issues@main
        with:
          pr_url: ${{github.event.pull_request.html_url}}
          format: IssueNumber

      - name: Move issue to In progress status
        run: >
          curl 'https://api.zenhub.com/p2/workspaces/6246bc1e8d5e5b0010c77c74/repositories/475419392/issues/${{ steps.links.outputs.issues }}/moves' \
            -H 'content-type: application/json' \
            -H 'x-authentication-token: ${{ secrets.ZENHUB_API_TOKEN }}' \
            --data-raw '{"pipeline_id":"Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzI4MzE0Mzg","position":"top"}' \
            --compressed
